language: cpp
install:
    - sudo apt-get install libwxgtk3.0-dev libwxgtk3.0-0

script:
    - mkdir build && cd build
    - cmake ../
    - make

notifications:
    email: false
    
git:
    depth: 10
